---
# tasks file for general

- name: install packages
  update_cache: yes
  apt: name={{ item }} state=present
  with_items:
    - docker.io
    - python3-pip
- name: Install docker-py python package.
  pip:
    name: docker-py